<a href="https://colab.research.google.com/github/tajjj3/Hacklytics-2023-MentalAir-App/blob/main/Hacklytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Collection**

In [ ]:
from google.colab import drive
from bs4 import BeautifulSoup
import requests, re
import pandas as pd
import numpy as np
def html_cleaner():
    col_title = []
    countries = []
    list_of_dat1 = []
    list_of_dat2 = []
    final_dat = []
    req = requests.get("https://stats.oecd.org/index.aspx?DataSetCode=BLI#")
    soup = BeautifulSoup(req.text, "html.parser")
    my_table = soup.find("table", class_ = "DataTable")
    heading = my_table.find("thead")
    find_tr = heading.find_all("tr")
    find_th = find_tr[3].find_all("th", class_ = "HDim")
    for item in find_th:
        text = item.text
        col_title.append(text)
    body = my_table.find("tbody")
    find_tr2 = body.find_all("tr")
    for item in range(0, len(find_tr2) - 4):
        country = find_tr2[item].find("td", colspan = "2")
        countries.append(country.text)
        if item % 2 == 0:
            data = find_tr2[item].find_all("td", class_ = "Data")
            listy = []
            for i in data:
                listy.append(i.text)
            list_of_dat1.append(listy)
        else:
            data = find_tr2[item].find_all("td", class_ = "Data2")
            listy_2 = []
            for i in data:
                listy_2.append(i.text)
            list_of_dat2.append(listy_2)
    zipping = list(zip(list_of_dat1, list_of_dat2))
    for tuplea in zipping:
        for lista in tuplea:
            final_dat.append(lista)
    for a_list in final_dat:
        for i in range(len(a_list)):
            if a_list[i] == "..":
                a_list[i] = "N/A"
    df = pd.DataFrame(data = final_dat, columns = col_title, index = countries)
    df.drop(["Dwellings without basic facilities", "Housing expenditure", "Rooms per person", "Household net adjusted disposable income" \
        , "Household net wealth", "Labour market insecurity", "Employment rate", "Long-term unemployment rate", "Educational attainment" \
        , "Student skills", "Years in education", "Water quality", "Stakeholder engagement for developing regulations", "Voter turnout" \
        , "Life expectancy", "Self-reported health", "Feeling safe walking alone at night", "Homicide rate"], axis = 1, inplace = True)
    return df
    
 ########### Website Link #############   
#https://stats.oecd.org/index.aspx?DataSetCode=BLI#


############ Function Call ############
html_cleaner()

,Personal earnings,Quality of support network,Air pollution,Life satisfaction,Employees working very long hours,Time devoted to leisure and personal care
Australia,55 206,93,6.7,7.1,12.5,14.36
Austria,53 132,92,12.2,7.2,5.3,14.51
Belgium,54 327,90,12.8,6.8,4.3,15.52
Canada,55 342,93,7.1,7,3.3,14.57
Chile,26 729,88,23.4,6.2,7.7,N/A
Colombia,N/A,80,22.6,5.7,23.7,N/A
Costa Rica,N/A,82,17.5,6.3,22,N/A
Czech Republic,29 885,96,17,6.9,4.5,N/A
Denmark,58 430,95,10,7.5,1.1,N/A
Estonia,30 720,95,5.9,6.5,2.2,14.98
Finland,46 230,96,5.5,7.9,3.6,15.17
France,45 581,94,11.4,6.7,7.7,16.2
Germany,53 745,90,12,7.3,3.9,15.62
Greece,27 207,78,14.5,5.8,4.5,15.03
Hungary,25 409,94,16.7,6,1.5,15.08
Iceland,67 488,98,6.4,7.6,11.7,N/A
Ireland,49 474,96,7.8,7,4.7,14.54
Israel,39 322,95,19.7,7.2,14.1,N/A
Italy,37 769,89,15.9,6.5,3.3,16.47
Japan,38 515,89,13.7,6.1,N/A,14.1
Korea,41 960,80,27.3,5.8,N/A,14.83
Latvia,29 876,92,12.7,6.2,1.6,N/A
Lithuania,31 811,89,10.5,6.4,1,N/A
Luxembourg,65 854,91,10,7.4,2.8,N/A
Mexico,16 230,77,20.3,6,27,N/A
Netherlands,58 828,94,12.2,7.5,0.3,15.45
New Zealand,45 269,95,6,7.3,14,14.87
Norway,55 780,96,6.7,7.3,1.4,15.67
Poland,32 527,94,22.8,6.1,4.2,14.68
Portugal,28 410,87,8.3,5.8,5.6,N/A
Slovak Republic,23 619,95,18.5,6.5,4.2,N/A
Slovenia,41 445,95,17,6.5,5.6,N/A
Spain,37 922,93,10,6.5,2.5,15.75
Sweden,47 020,94,5.8,7.3,0.9,N/A
Switzerland,64 824,94,10.1,7.5,0.4,N/A
Türkiye,N/A,85,27.1,4.9,25,14.61
United Kingdom,47 147,93,10.1,6.8,10.8,14.94
United States,69 392,94,7.7,7,10.4,14.57

# **Data Manipulation**

In [ ]:
import requests, re
import pandas as pd
import numpy as np
def insight_2():
    df_1 = pd.read_csv("api_clean.csv")
    country_list_1 = []
    pollution_list = []
    countries_1 = df_1.iloc[:,0]
    for item in countries_1:
        country_list_1.append(item)
    pollution = df_1.iloc[:,3]
    for item in pollution:
        pollution_list.append(item)
    zipping_1 = list(zip(pollution_list,country_list_1))
    
    
    
    df_2 = pd.read_csv("world_happiness.csv")
    happiness_list = []
    country_list_2 = []
    happiness = df_2.iloc[:,2]
    for item in happiness:
        happiness_list.append(item)
    countries_2 = df_2.iloc[:,1]
    for item in countries_2:
        country_list_2.append(item)
    
    zipping_2 = list(zip(country_list_2,happiness_list))
    updated_list = []
    for tup in zipping_2:
        if tup[0] in country_list_1:
            updated_list.append(list(tup))
    
    for tup_1 in zipping_1:
        for a_list in updated_list:
            if tup_1[1] == a_list[0]:
                a_list.append(tup_1[0])
    
    new_df = pd.DataFrame(data = updated_list, columns = ["Country Name", "Happiness Score", "Air Pollution"])
    return new_df




############ Function Call ############
insight_2()

      Country Name  Happiness Score  Air Pollution
0          Finland            7.821            5.5
1          Denmark            7.636           10.0
2          Iceland            7.557            6.4
3      Switzerland            7.512           10.1
4      Netherlands            7.415           12.2
5           Sweden            7.384            5.8
6           Norway            7.365            6.7
7           Israel            7.364           19.7
8      New Zealand            7.200            6.0
9          Austria            7.163           12.2
10       Australia            7.162            6.7
11         Ireland            7.041            7.8
12         Germany            7.034           12.0
13          Canada            7.025            7.1
14   United States            6.977            7.7
15  United Kingdom            6.943           10.1
16         Belgium            6.805           12.8
17          France            6.687           11.4
18        Slovenia            6.630           17.0
19      Costa Rica            6.582           17.5
20           Spain            6.476           10.0
21           Italy            6.467           15.9
22       Lithuania            6.446           10.5
23         Estonia            6.341            5.9
24          Latvia            6.180           12.7
25           Chile            6.172           23.4
26          Mexico            6.128           20.3
27          Poland            6.123           22.8
28         Hungary            6.086           16.7
29           Japan            6.039           13.7
30        Portugal            6.016            8.3
31          Greece            5.948           14.5
32        Colombia            5.781           22.6

# **Data Visualization**

In [ ]:
import plotly.express as px
import pandas as pd
def visual2():
    df = pd.read_csv("api_clean.csv")
    fig = px.scatter(df, x = df.loc[:,"Air pollution"], y = df.loc[:,"Life satisfaction"], trendline = "ols", trendline_color_override="black", \
                     labels = {"Air pollution": "Air pollution", "Life satisfaction": "Life Satisfaction"}, title = "Life Satisfaction vs. Air Pollution")
    return fig.show()




############ Function Call ############
visual2()